name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '4.0'
          - '3.4'
          - '3.3'
          - '3.2'
          - '2.6'
        include:
          - ruby: '4.0'
            experimental: true

    continue-on-error: ${{ matrix.experimental || false }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: ${{ matrix.ruby != '2.6' }}
      - name: Bundle install (Ruby 2.6)
        if: matrix.ruby == '2.6'
        run: bundle install --jobs 4
      - name: Run the default task
        run: bundle exec rake
